# configure local docker image in values-minikube.yaml before running `helm install`

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

## deployed withh emptyDir
volumes:
 persistence: false

# disabled AntiAffinity
affinity:
 anti_affinity: false

# disable auto recovery
components:
 autorecovery: false
 pulsar_manager: true

zookeeper:
  configData:
    PULSAR_MEM: >
      -Xms128m -Xmx512m
  replicaCount: 1

bookkeeper:
  configData:
    PULSAR_MEM: >
      -Xms128m -Xmx512m
  replicaCount: 1

broker:
  replicaCount: 3
  configData:
    PULSAR_MEM: >
      -Xms128m -Xmx512m
  autoSkipNonRecoverableData: "true"
  # storage settings
  managedLedgerDefaultEnsembleSize: "1"
  managedLedgerDefaultWriteQuorum: "1"
  managedLedgerDefaultAckQuorum: "1"
  loadBalancerLoadSheddingStrategy: "org.apache.pulsar.broker.loadbalance.extensions.scheduler.TransferShedder"
  loadManagerClassName: "org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImpl"

proxy:
  replicaCount: 1
  configData:
    PULSAR_MEM: >
      -Xms128m -Xmx512m

# default image tag for pulsar images
# uses chart's appVersion when unspecified
defaultPulsarImageTag: new-loadmanager-test

## Images
##
## Control what images to use for each component
images:
 zookeeper:
  repository: apachepulsar/pulsar-all
  # uses defaultPulsarImageTag when unspecified
  tag: new-loadmanager-test
  pullPolicy: IfNotPresent
 bookie:
  repository: apachepulsar/pulsar-all
  # uses defaultPulsarImageTag when unspecified
  tag: new-loadmanager-test
  pullPolicy: IfNotPresent
 autorecovery:
  repository: apachepulsar/pulsar-all
  # uses defaultPulsarImageTag when unspecified
  tag: new-loadmanager-test
  pullPolicy: IfNotPresent
 broker:
  repository: apachepulsar/pulsar-all
  # uses defaultPulsarImageTag when unspecified
  tag: new-loadmanager-test
  pullPolicy: IfNotPresent
 proxy:
  repository: apachepulsar/pulsar-all
  # uses defaultPulsarImageTag when unspecified
  tag: new-loadmanager-test
  pullPolicy: IfNotPresent
 functions:
  repository: apachepulsar/pulsar-all
  # uses defaultPulsarImageTag when unspecified
  tag: new-loadmanager-test
 pulsar_manager:
  repository: apachepulsar/pulsar-manager
  tag: v0.3.0
  pullPolicy: IfNotPresent
  hasCommand: false



## Pulsar Zookeeper metadata. The metadata will be deployed as
## soon as the last zookeeper node is reachable. The deployment
## of other components that depends on zookeeper, such as the
## bookkeeper nodes, broker nodes, etc will only start to be
## deployed when the zookeeper cluster is ready and with the
## metadata deployed
pulsar_metadata:
  component: pulsar-init
  image:
    repository: apachepulsar/pulsar-all
    tag: new-loadmanager-test
    pullPolicy: IfNotPresent
  configurationStoreMetadataPrefix: ""
  configurationStorePort: 2181
  configData:
    PULSAR_MEM: >
      -Xms128m -Xmx512m
